topics:
  input:
    image: "/anafi/image"
  output:
    boxes: "/yolo/search/boxes"
    detectionImage: "/yolo/search/detectionImage"

settings:
  publish_detection_images: True
  print_terminal_output: True

model:
  path: "/home/simenallum/catkin_ws/src/yolov8_ros/yolo_network_config/models/large_small_objects.pt"
  confidence_threshold: 0.7
  iou_threshold: 0.5

control:
  service:
    process_image: "search_process_image"
    process_next_image: "search_process_next_image"
  
