topics:
  input:
    image: "/anafi/image"
  output:
    boxes: "/yolo/platform/boxes"
    detectionImage: "/yolo/platform/detectionImage"

settings:
  publish_detection_images: False

model:
  path: "/home/simenallum/catkin_ws/src/yolov8_ros/yolo_network_config/models/humans_and_bouys.pt"
